//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShareViewer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.8.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Control")]
        public global::System.Drawing.Color BackgroundColor {
            get {
                return ((global::System.Drawing.Color)(this["BackgroundColor"]));
            }
            set {
                this["BackgroundColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Default")]
        public string ExtraFolder {
            get {
                return ((string)(this["ExtraFolder"]));
            }
            set {
                this["ExtraFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Default")]
        public string AllTablesFolder {
            get {
                return ((string)(this["AllTablesFolder"]));
            }
            set {
                this["AllTablesFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.bsb-software.de/rese/")]
        public string SharesUrl {
            get {
                return ((string)(this["SharesUrl"]));
            }
            set {
                this["SharesUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Inhalt.txt")]
        public string DataDaysListingFilename {
            get {
                return ((string)(this["DataDaysListingFilename"]));
            }
            set {
                this["DataDaysListingFilename"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"Row,Date,Day,TimeFrom,TimeTo,F,FP,FV\"")]
        public string InitialAllTableView {
            get {
                return ((string)(this["InitialAllTableView"]));
            }
            set {
                this["InitialAllTableView"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AllTableDataStart {
            get {
                return ((string)(this["AllTableDataStart"]));
            }
            set {
                this["AllTableDataStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AllTableDataEnd {
            get {
                return ((string)(this["AllTableDataEnd"]));
            }
            set {
                this["AllTableDataEnd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AllTableTradingSpan {
            get {
                return ((string)(this["AllTableTradingSpan"]));
            }
            set {
                this["AllTableTradingSpan"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Make Slow (Five minutes) Prices SP,0,2,4,6,7,8,10,11,18,21,24</string>
  <string>Make Five minutes Price Gradients PG,0,2,4,6,7,8,10,11,12,18,19,21,22,24,25</string>
  <string>Related volume Figure (RPGFV) of biggest PGF,0,2,4,6,7,8,10,48</string>
  <string>Identify Lazy Shares,0,2,4,6,7,8,10,48</string>
  <string>Columns 70-80,0,2,6,7,10,48,69,70,71,72,73,74,75,76,77,78,79</string>
  <string>Find direction and Turning,0,2,4,6,7,8,10,11,12,18,19,21,22,24,25,67</string>
  <string>Find Five minutes Gradients Figure PGF,0,2,4,6,7,8,10,12,13,14,15,16</string>
  <string>Make High Line HL,0,2,4,6,7,8,10,22,25,28,29,32,33,69,70</string>
  <string>Make Low Line LL,0,2,4,6,7,8,10,22,25,38,39,42,43,72,73</string>
  <string>Make Slow Volumes SV,0,2,4,6,7,8,10,48,50,54,58,61</string>
  <string>Slow Volume Figure SVFac,0,2,4,6,7,8,10,48,50,51,52,58,75</string>
  <string>Slow Volume Figure SVFbd,0,2,4,6,7,8,10,48,54,55,56,61,76</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection AllTableViews {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["AllTableViews"]));
            }
            set {
                this["AllTableViews"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>2017/12/25 = Christmas</string>
  <string>2017/12/26 = 2nd Day of Christmas</string>
  <string>2018/01/01 = New Years Day</string>
  <string>2018/03/30 = Good Friday</string>
  <string>2018/04/02 = Easter Monday</string>
  <string>2018/05/01 = Labour Day</string>
  <string>2018/05/10 = Ascension Day</string>
  <string>2018/05/21 = Whit Monday</string>
  <string>2018/05/31 = Corpus Christi</string>
  <string>2018/10/03 = Day of German Unity</string>
  <string>2018/12/25 = Christmas</string>
  <string>2018/12/26 = 2nd Day of Christmas</string>
  <string>2019/01/01 = New Years Day</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Holidays {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Holidays"]));
            }
            set {
                this["Holidays"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>All Columns,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27</string>
  <string>Initial,0,1,2,3,4,5</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection OverviewViews {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["OverviewViews"]));
            }
            set {
                this["OverviewViews"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        [global::System.Configuration.SettingsManageabilityAttribute(global::System.Configuration.SettingsManageability.Roaming)]
        public bool UpgradeRequired {
            get {
                return ((bool)(this["UpgradeRequired"]));
            }
            set {
                this["UpgradeRequired"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<LazyShareParam xmlns:xsi=\"http://www.w3" +
            ".org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <" +
            "From>1000</From>\r\n  <To>1000000</To>\r\n  <Setting>7000</Setting>\r\n</LazySharePara" +
            "m>")]
        public global::ShareViewer.LazyShareParam ParamsLazyShare {
            get {
                return ((global::ShareViewer.LazyShareParam)(this["ParamsLazyShare"]));
            }
            set {
                this["ParamsLazyShare"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<DirectionAndTurningParam xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <From>0.99999</From>
  <To>1.01</To>
  <Z>1</Z>
  <PGcThreshold>100000</PGcThreshold>
</DirectionAndTurningParam>")]
        public global::ShareViewer.DirectionAndTurningParam ParamsDirectionAndTurning {
            get {
                return ((global::ShareViewer.DirectionAndTurningParam)(this["ParamsDirectionAndTurning"]));
            }
            set {
                this["ParamsDirectionAndTurning"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<FiveMinsGradientFigureParam xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <XMin>1</XMin>
  <XMax>5</XMax>
  <X>0</X>
  <YMin>0</YMin>
  <YMax>0.005</YMax>
  <Y>0</Y>
  <ZMin>104</ZMin>
  <ZMax>999</ZMax>
  <Z>0</Z>
</FiveMinsGradientFigureParam>")]
        public global::ShareViewer.FiveMinsGradientFigureParam ParamsFiveMinsGradientFigure {
            get {
                return ((global::ShareViewer.FiveMinsGradientFigureParam)(this["ParamsFiveMinsGradientFigure"]));
            }
            set {
                this["ParamsFiveMinsGradientFigure"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<MakeHighLineParam xmlns:xsi=\"http://www" +
            ".w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n" +
            "  <ZMin>0</ZMin>\r\n  <ZMax>0.001</ZMax>\r\n  <Z>0.0005</Z>\r\n</MakeHighLineParam>")]
        public global::ShareViewer.MakeHighLineParam ParamsMakeHighLine {
            get {
                return ((global::ShareViewer.MakeHighLineParam)(this["ParamsMakeHighLine"]));
            }
            set {
                this["ParamsMakeHighLine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<MakeLowLineParam xmlns:xsi=\"http://www." +
            "w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n " +
            " <ZMin>0</ZMin>\r\n  <ZMax>0.01</ZMax>\r\n  <Z>0.005</Z>\r\n</MakeLowLineParam>")]
        public global::ShareViewer.MakeLowLineParam ParamsMakeLowLine {
            get {
                return ((global::ShareViewer.MakeLowLineParam)(this["ParamsMakeLowLine"]));
            }
            set {
                this["ParamsMakeLowLine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<SlowVolFigSVFacParam xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <XMin>1</XMin>
  <XMax>5</XMax>
  <X>1</X>
  <YMin>0</YMin>
  <YMax>0.005</YMax>
  <Y>0</Y>
  <ZMin>104</ZMin>
  <ZMax>999</ZMax>
  <Z>104</Z>
  <WMin>1</WMin>
  <WMax>99</WMax>
  <W>1</W>
</SlowVolFigSVFacParam>")]
        public global::ShareViewer.SlowVolFigSVFacParam ParamsSlowVolFigSVFac {
            get {
                return ((global::ShareViewer.SlowVolFigSVFacParam)(this["ParamsSlowVolFigSVFac"]));
            }
            set {
                this["ParamsSlowVolFigSVFac"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<SlowVolFigSVFbdParam xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <ZMin>104</ZMin>
  <ZMax>2000</ZMax>
  <Z>104</Z>
  <YMin>0</YMin>
  <YMax>0.005</YMax>
  <Y>0</Y>
  <WMin>1</WMin>
  <WMax>99</WMax>
  <W>1</W>
</SlowVolFigSVFbdParam>")]
        public global::ShareViewer.SlowVolFigSVFbdParam ParamsSlowVolFigSVFbd {
            get {
                return ((global::ShareViewer.SlowVolFigSVFbdParam)(this["ParamsSlowVolFigSVFbd"]));
            }
            set {
                this["ParamsSlowVolFigSVFbd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<SlowPriceParam xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <ZMin>100</ZMin>
  <ZMax>99999</ZMax>
  <Z>100</Z>
  <YMin>0</YMin>
  <YMax>0.9999</YMax>
  <Ya>0.98</Ya>
  <Yb>0.95</Yb>
  <Yc>0.8</Yc>
  <Yd>0.7</Yd>
</SlowPriceParam>")]
        public global::ShareViewer.SlowPriceParam ParamsSlowPrice {
            get {
                return ((global::ShareViewer.SlowPriceParam)(this["ParamsSlowPrice"]));
            }
            set {
                this["ParamsSlowPrice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<MakeSlowVolumeParam xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <XMin>0.4</XMin>
  <XMax>1</XMax>
  <X>0.5</X>
  <YMin>0</YMin>
  <YMax>0.9999</YMax>
  <Ya>0.1</Ya>
  <Yb>0.1</Yb>
  <Yc>0.1</Yc>
  <Yd>0.1</Yd>
</MakeSlowVolumeParam>")]
        public global::ShareViewer.MakeSlowVolumeParam ParamsMakeSlowVolume {
            get {
                return ((global::ShareViewer.MakeSlowVolumeParam)(this["ParamsMakeSlowVolume"]));
            }
            set {
                this["ParamsMakeSlowVolume"] = value;
            }
        }
    }
}
